package services

import models.{Computer, Company}
import kr.hconnect.core.spring.Springs
import repository.{ComputerJpaRepository, CompanyJpaRepository}
import org.springframework.transaction.annotation.Transactional
import play.api.Logger
import org.slf4j.LoggerFactory

/**
 * Setup
 * Created by debop on 2014. 1. 23..
 */
object Setup {

    lazy val log = LoggerFactory.getLogger(getClass)

    lazy val companyRepository = Springs.getBean(classOf[CompanyJpaRepository])
    lazy val computerRepository = Springs.getBean(classOf[ComputerJpaRepository])

    @Transactional
    def buildSampleData() {
        log.info("샘플 데이터를 생성합니다...")

        buildCompany()
        buildComputer()

        log.info("샘플 데이터 생성을 완료했습니다.")
    }


    private def buildCompany() {
        companyNames.foreach(name => {
            val company = Company(0, name)
            companyRepository.save(company)
        })
        companyRepository.flush()
    }

    private def buildComputer() {
        computers.foreach((x: (String, String, String, Any)) => {
            // val company = if(x._4 != null) companyRepository.findOne(x._4.asInstanceOf[Long]) else None
            val companyId = x._4 match {
                case x: Integer => Some(x.toLong)
                case x: Long => Some(x)
                case null => None
            }
            val computer = Computer(None, x._1, None, None, companyId)
            computerRepository.save(computer)
        })
        computerRepository.flush()
    }

    lazy val companyNames = Seq(
        "Apple Inc.",
        "Thining Machines",
        "RCA",
        "Netronics",
        "Tandy Corporation",
        "MOS Technology",
        "Micro Instrumentation and Telemetry Systems",
        "IMS Associates, Inc.",
        "Digital Equipment Corporation",
        "Lincoln Laboratory",
        "Moore School of Electrical Engineering",
        "IBM",
        "Amiga Corporation",
        "Canon",
        "Nokia",
        "Sony",
        "OQO",
        "NeXT",
        "Atari",
        "Acorn computer",
        "Timex Sinclair",
        "Nintendo",
        "Sinclair Research Ltd",
        "Xerox",
        "Hewlett-Packard",
        "Zemmix",
        "ACVS",
        "Sanyo",
        "Cray",
        "Evans & Sutherland",
        "E.S.R. Inc.",
        "OMRON",
        "BBN Technologies",
        "Lenovo Group",
        "ASUS",
        "Amstrad",
        "Sun Microsystems",
        "Texas Instruments",
        "HTC Corporation",
        "Research In Motion",
        "Samsung Electronics"
    )

    lazy val computers = Seq(
        ("MacBook Pro 15.4 inch", null, null, 1),
        ("CM-2a", null, null, 2),
        ("CM-200", null, null, 2),
        ("CM-5e", null, null, 2),
        ("CM-5", "1991-01-01", null, 2),
        ("MacBook Pro", "2006-01-10", null, 1),
        ("Apple IIe", null, null, null),
        ("Apple IIc", null, null, null),
        ("Apple IIGS", null, null, null),
        ("Apple IIc Plus", null, null, null),
        ("Apple II Plus", null, null, null),
        ("Apple III", "1980-05-01", "1984-04-01", 1),
        ("Apple Lisa", null, null, 1),
        ("CM-2", null, null, 2),
        ("Connection Machine", "1987-01-01", null, 2),
        ("Apple II", "1977-04-01", "1993-10-01", 1),
        ("Apple III Plus", "1983-12-01", "1984-04-01", 1),
        ("COSMAC ELF", null, null, 3),
        ("COSMAC VIP", "1977-01-01", null, 3),
        ("ELF II", "1977-01-01", null, 4),
        ("Macintosh", "1984-01-24", null, 1),
        ("Macintosh II", null, null, null),
        ("Macintosh Plus", "1986-01-16", "1990-10-15", 1),
        ("Macintosh IIfx", null, null, null),
        ("iMac", "1998-01-01", null, 1),
        ("Mac Mini", "2005-01-22", null, 1),
        ("Mac Pro", "2006-08-07", null, 1),
        ("Power Macintosh", "1994-03-01", "2006-08-01", 1),
        ("PowerBook", "1991-01-01", "2006-01-01", 1),
        ("Xserve", null, null, null),
        ("Powerbook 100", null, null, null),
        ("Powerbook 140", null, null, null),
        ("Powerbook 170", null, null, null),
        ("PowerBook Duo", null, null, null),
        ("PowerBook 190", null, null, null),
        ("Macintosh Quadra", "1991-01-01", null, 1),
        ("Macintosh Quadra 900", null, null, null),
        ("Macintosh Quadra 700", null, null, null),
        ("Macintosh LC", "1990-01-01", null, 1),
        ("Macintosh LC II", "1990-01-01", null, 1),
        ("Macintosh LC III", "1993-01-01", null, 1),
        ("Macintosh LC III+", null, null, null),
        ("Macintosh Quadra 605", "1993-10-21", null, 1),
        ("Macintosh LC 500 series", null, null, null),
        ("TRS-80 Color Computer", "1980-01-01", null, 5),
        ("Acorn System 2", null, null, null),
        ("Dragon 32/64", null, null, null),
        ("MEK6800D2", null, null, null),
        ("Newbear 77/68", null, null, null),
        ("Commodore PET", null, null, 6),
        ("Commodore 64", "1982-08-01", "1994-01-01", 6),
        ("Commodore 64C", null, null, null),
        ("Commodore SX-64", null, null, 6),
        ("Commodore 128", null, null, 6),
        ("Apple I", "1976-04-01", "1977-10-01", 1),
        ("KIM-1", "1975-01-01", null, 7),
        ("Altair 8800", "1974-12-19", null, 8),
        ("IMSAI 8080", "1975-08-01", null, 9),
        ("IMSAI Series Two", null, null, null),
        ("VAX", "1977-10-25", null, 10),
        ("VAX 11/780", "1977-10-25", null, 10),
        ("VAX 11/750", "1980-10-01", null, 10),
        ("TX-2", "1958-01-01", null, 11),
        ("TX-0", "1956-01-01", null, 11),
        ("Whirlwind", "1951-04-20", null, 11),
        ("ENIAC", "1946-02-15", "1955-10-02", 12),
        ("IBM PC", "1981-08-12", null, 13),
        ("Macintosh Classic", null, null, null),
        ("Macintosh Classic II", "1991-01-01", null, 1),
        ("Amiga", "1985-01-01", null, 14),
        ("Amiga 1000", null, null, 6),
        ("Amiga 500", "1987-01-01", null, 6),
        ("Amiga 500+", null, null, null),
        ("Amiga 2000", "1986-01-01", "1990-01-01", 6),
        ("Amiga 3000", null, null, 6),
        ("Amiga 600", "1992-03-01", null, 6),
        ("Macintosh 128K", "1984-01-01", null, 1),
        ("Macintosh 512K", "1984-09-10", "1986-04-14", 1),
        ("Macintosh SE", "1987-03-02", "1989-08-01", 1),
        ("Macintosh SE/30", "1989-01-19", "1991-10-21", 1),
        ("Canon Cat", "1987-01-01", null, 15),
        ("Nokia 770", null, null, 16),
        ("Nokia N800", "2007-01-01", null, 16),
        ("Mylo", "2006-09-21", null, 17),
        ("OQO 02", "2007-01-01", null, 18),
        ("OQO 01+", null, null, null),
        ("Pinwheel calculator", null, null, null),
        ("iBook", null, null, 1),
        ("MacBook", "2006-05-16", null, 1),
        ("NeXTstation", "1990-01-01", "1993-01-01", 19),
        ("NeXTcube", "1988-01-01", "1993-01-01", 19),
        ("NeXTstation Color Turbo", null, null, null),
        ("NeXTstation Color", null, null, null),
        ("NeXTstation Turbo", null, null, null),
        ("NeXTcube Turbo", null, null, 19),
        ("NeXTcube 040", null, null, 19),
        ("NeXTcube 030", null, null, 19),
        ("Tinkertoy Tic-Tac-Toe Computer", null, null, null),
        ("Z3", null, null, null),
        ("Z4", null, null, null),
        ("Z1", null, null, null),
        ("Z2", null, null, null),
        ("Wang 2200", "1973-05-01", null, null),
        ("Wang VS", null, null, null),
        ("Wang OIS", null, null, null),
        ("BBC Micro", null, null, 22),
        ("IBM 650", "1953-01-01", "1962-01-01", 13),
        ("Cray-1", null, null, null),
        ("Cray-3", null, null, null),
        ("Cray-2", null, null, null),
        ("Cray-4", null, null, null),
        ("Cray X1", null, null, null),
        ("Cray XD1", null, null, null),
        ("Cray T3D", "1993-01-01", null, null),
        ("Cray T3E", "1995-01-01", null, null),
        ("Cray C90", null, null, null),
        ("Cray T90", null, null, null),
        ("Cray SV1", null, null, null),
        ("Cray J90", null, null, null),
        ("Cray XT3", null, null, null),
        ("Cray CS6400", null, null, null),
        ("Atari ST", "1985-01-01", "1993-01-01", 20),
        ("Amiga 2500", null, null, null),
        ("Amiga 2500", null, null, 6),
        ("Amiga 4000", null, null, 6),
        ("Amiga 3000UX", null, null, 6),
        ("Amiga 3000T", null, null, 6),
        ("Amiga 4000T", null, null, 6),
        ("Amiga 1200", "1992-10-01", "1996-01-01", 6),
        ("Atari 1040 STf", "1986-01-01", null, null),
        ("Atari 520 ST", "1985-01-01", null, null),
        ("Atari 520 STfm", "1986-01-01", null, null),
        ("Atari 1040 STe", "1989-01-01", null, null),
        ("Atari MEGA STe", "1991-01-01", null, null),
        ("Atari 520 ST+", "1985-01-01", null, null),
        ("Atari 520 STm", "1985-01-01", null, null),
        ("Atari 130 ST", "1985-01-01", null, null),
        ("Atari 260 ST", "1985-01-01", null, null),
        ("Atari MEGA ST", "1987-01-01", null, null),
        ("Atari 520 STf", "1986-01-01", null, null),
        ("Atari 1040 STfm", "1986-01-01", null, null),
        ("Atari 2080 ST", "1986-01-01", null, null),
        ("Atari 260 ST+", "1985-01-01", null, null),
        ("Atari 4160 STe", "1988-01-01", null, null),
        ("TRS-80 Color Computer 2", null, null, null),
        ("TRS-80 Color Computer 3", null, null, null),
        ("TRS-80 Model 1", "1977-01-01", null, 5),
        ("Timex Sinclair 2068", "1983-11-01", "1984-04-01", 23),
        ("ZX Spectrum", "1982-01-01", null, 25),
        ("Xerox Star", "1981-01-01", null, 26),
        ("Xerox Alto", null, null, null),
        ("Acorn Archimedes", null, null, 22),
        ("Nintendo Entertainment System", null, null, 24),
        ("Super Nintendo Entertainment System", "1991-08-01", "1999-01-01", 24),
        ("Super Famicom", null, null, null),
        ("Nintendo GameCube", null, null, 24),
        ("Game Boy line", null, null, null),
        ("PlayStation", "1994-12-03", null, 17),
        ("PlayStation 2", "2000-03-24", null, 17),
        ("Game & Watch", null, null, 24),
        ("EDSAC", null, null, null),
        ("IBM System/4 Pi", null, null, null),
        ("IBM AP-101", null, null, null),
        ("IBM TC-1", null, null, null),
        ("IBM AP-101B", null, null, null),
        ("IBM AP-101S", null, null, 13),
        ("ProLiant", null, null, 27),
        ("Http://nepomuk.semanticdesktop.org/xwiki/", null, null, null),
        ("Sinclair QL", "1984-01-01", "1986-01-01", 25),
        ("Sinclair ZX81", "1981-01-01", null, 25),
        ("Sinclair ZX80", null, null, 25),
        ("Atari 65XE", null, null, 20),
        ("Deep Blue", null, null, null),
        ("Macintosh Quadra 650", null, null, null),
        ("Macintosh Quadra 610", null, null, null),
        ("Macintosh Quadra 800", null, null, null),
        ("Macintosh Quadra 950", null, null, null),
        ("PowerBook 160", null, null, null),
        ("PowerBook 145B", null, null, null),
        ("PowerBook 170", null, null, null),
        ("PowerBook 145", null, null, null),
        ("PowerBook G3", null, null, null),
        ("PowerBook 140", null, null, null),
        ("Macintosh IIcx", null, null, null),
        ("Powerbook 180", null, null, null),
        ("PowerBook G4", null, null, null),
        ("Macintosh XL", null, null, null),
        ("PowerBook 100", null, null, null),
        ("PowerBook 2400c", null, null, null),
        ("PowerBook 1400", null, null, null),
        ("Macintosh Quadra 630", null, null, null),
        ("Macintosh Quadra 660AV", null, null, null),
        ("Macintosh Quadra 840AV", null, null, null),
        ("PowerBook 5300", null, null, null),
        ("PowerBook 3400c", null, null, null),
        ("Macintosh Color Classic", null, null, null),
        ("Macintosh 512Ke", null, null, null),
        ("Macintosh IIsi", null, null, null),
        ("Macintosh IIx", null, null, null),
        ("PowerBook 500 series", null, null, null),
        ("Power Macintosh G3", null, null, null),
        ("Macintosh IIci", null, null, null),
        ("iMac G5", "2004-08-31", null, 1),
        ("Power Mac G4", null, null, null),
        ("Power Macintosh 7100", null, null, null),
        ("Power Macintosh 9600", null, null, null),
        ("Power Macintosh 7200", null, null, null),
        ("Power Macintosh 7300", null, null, null),
        ("Power Macintosh 8600", null, null, null),
        ("Power Macintosh 6200", null, null, null),
        ("Power Macintosh 8100", null, null, null),
        ("Compact Macintosh", null, null, null),
        ("Power Macintosh 4400", null, null, null),
        ("Power Macintosh 9500", null, null, null),
        ("Macintosh Portable", null, null, null),
        ("EMac", null, null, null),
        ("Power Macintosh 7600", null, null, null),
        ("Power Mac G5", null, null, null),
        ("Power Macintosh 7500", null, null, null),
        ("Power Macintosh 6100", null, null, null),
        ("Power Macintosh 8500", null, null, null),
        ("Macintosh IIvi", null, null, null),
        ("Macintosh IIvx", null, null, null),
        ("IMac G3", null, null, null),
        ("IMac G4", null, null, null),
        ("Power Mac G4 Cube", null, null, 1),
        ("Intel iMac", null, null, null),
        ("Deep Thought", null, null, 13),
        ("Wii", "2006-11-19", null, 24),
        ("IBM System x", null, null, null),
        ("IBM System i", "2006-01-01", null, 13),
        ("IBM System z", "2006-01-01", null, 13),
        ("IBM System p", "2000-01-01", null, 13),
        ("LC 575", null, null, null),
        ("Macintosh TV", null, null, null),
        ("Macintosh Performa", null, null, null),
        ("Macintosh II series", null, null, null),
        ("Power Macintosh 6400", null, null, null),
        ("Power Macintosh 6500", null, null, null),
        ("Apple PenLite", null, null, null),
        ("Wallstreet", null, null, null),
        ("Twentieth Anniversary Macintosh", null, null, null),
        ("Power Macintosh 5500", null, null, null),
        ("iBook G3", null, null, 1),
        ("Power Macintosh 5200 LC", null, null, null),
        ("Power Macintosh 5400", null, null, null),
        ("CM-1", null, null, null),
        ("MSX", "1983-01-01", "1995-01-01", 28),
        ("PlayStation 3", null, null, 17),
        ("MSX2", "1986-01-01", null, 29),
        ("MSX2+", "1988-01-01", null, 30),
        ("MSX turbo R", "1990-01-01", null, null),
        ("Panasonic FS A1GT", null, null, null),
        ("Panasonic FS A1ST", null, null, null),
        ("PDP-11", null, null, 10),
        ("PDP-1", null, null, 10),
        ("PDP-10", null, null, 10),
        ("PDP-8", null, null, 10),
        ("PDP-6", null, null, 10),
        ("DECSYSTEM-20", null, null, 10),
        ("PDP-7", null, null, 10),
        ("PDP-5", null, null, 10),
        ("PDP-12", null, null, 10),
        ("LINC", null, null, 10),
        ("PDP-14", null, null, 10),
        ("PDP-15", null, null, 10),
        ("PDP-16", null, null, 10),
        ("Cray X2", "2007-01-01", null, 31),
        ("Cray X-MP", "1982-01-01", null, 31),
        ("Evans & Sutherland ES-1", null, null, 32),
        ("Commodore VIC-20", "1980-01-01", null, 6),
        ("PowerBook 150", null, null, null),
        ("MacBook Air", "2008-01-15", null, 1),
        ("Digi-Comp I", "1963-01-01", null, 33),
        ("Digi-Comp", null, null, null),
        ("Digi-Comp II", null, null, 33),
        ("Manchester Mark I", "1949-01-01", null, null),
        ("Small-Scale Experimental Machine", "1948-01-01", null, null),
        ("Nintendo 64", null, null, 24),
        ("Game Boy Advance", null, null, 24),
        ("Game Boy", null, null, 24),
        ("Nintendo DS Lite", null, null, 24),
        ("Nintendo DS", "2004-01-01", null, 24),
        ("Game Boy Color", null, null, 24),
        ("Game Boy Advance SP", null, null, 24),
        ("Virtual Boy", null, null, 24),
        ("Game Boy Micro", null, null, 24),
        ("Roadrunner", null, null, 13),
        ("HP 9000", null, null, null),
        ("OMRON Luna-88K2", null, null, null),
        ("OMRON Luna-88K", null, null, 34),
        ("Motorola series 900", null, null, null),
        ("Motorola M8120", null, null, null),
        ("Triton Dolphin System 100", null, null, null),
        ("BBN TC2000", "1989-08-01", null, 35),
        ("WRT54G", null, null, null),
        ("ThinkPad", "1992-01-01", null, 36),
        ("Apple Newton", "1993-01-01", "1998-01-01", 1),
        ("Atanasoff-Berry Computer", "1937-01-01", null, null),
        ("Atlas Computer", "1962-01-01", "1974-01-01", null),
        ("ASUS Eee PC 901", null, null, 37),
        ("ASUS Eee PC 701", null, null, null),
        ("IBM 7030", "1961-01-01", null, 13),
        ("System/38", "1979-01-01", null, 13),
        ("System/36", "1983-01-01", "2000-01-01", 13),
        ("IBM 7090", "1959-01-01", null, 13),
        ("IBM RT", null, null, 13),
        ("System/360", "1964-01-01", null, 13),
        ("IBM 801", "1980-01-01", null, 13),
        ("IBM 1401", "1959-01-01", null, 13),
        ("ASCI White", "2001-01-01", "2006-01-01", 13),
        ("Blue Gene", null, null, 13),
        ("ASCI Blue Pacific", "1998-01-01", null, 13),
        ("iPhone", "2007-06-01", null, 1),
        ("Nokia N810", "2007-10-17", null, 16),
        ("EDSAC 2", null, null, null),
        ("Titan", null, null, null),
        ("Pilot ACE", null, null, null),
        ("HP Mini 1000", "2008-10-29", null, 27),
        ("HP 2133 Mini-Note PC", "2008-04-15", null, 27),
        ("Kogan Agora Pro", "2008-12-04", null, null),
        ("D-Series Machines", null, null, null),
        ("ZX Spectrum 48K", "1982-01-01", null, 25),
        ("ZX Spectrum 16K", "1982-01-01", null, 25),
        ("ZX Spectrum 128", "1985-09-01", null, 25),
        ("ZX Spectrum +3", null, null, 38),
        ("ZX Spectrum +2", "1986-01-01", null, 38),
        ("ZX Spectrum +2A", "1987-01-01", null, 38),
        ("ZX Spectrum +", "1984-06-01", null, 25),
        ("Acer Extensa", null, null, null),
        ("Acer Extensa 5220", null, null, null),
        ("Dell Latitude", null, null, null),
        ("Toshiba Satellite", null, null, null),
        ("Timex Sinclair 2048", null, null, 23),
        ("Sprinter", null, null, null),
        ("Timex Computer 2048", null, null, null),
        ("Pentagon", null, null, null),
        ("Belle", null, null, null),
        ("Loki", null, null, 25),
        ("Hobbit", null, null, null),
        ("NeXT Computer", null, null, 19),
        ("TRS-80", null, null, null),
        ("TRS-80 Model 2", "1980-01-01", null, 5),
        ("TRS-80 Model 3", null, null, 5),
        ("STacy", "1989-01-01", null, null),
        ("ST BOOK", "1990-01-01", null, null),
        ("Atari 520 STE", "1989-01-01", null, null),
        ("Amiga 2000 Model A", null, null, null),
        ("Amiga 2000 Model B", null, null, null),
        ("Amiga 2000 Model C", null, null, null),
        ("IBM 3270", null, null, null),
        ("CALDIC", null, null, null),
        ("Modbook", null, null, null),
        ("Compaq SystemPro", null, null, null),
        ("ARRA", null, null, null),
        ("IBM System Cluster 1350", null, null, null),
        ("Finite element machine", null, null, null),
        ("ES7000", null, null, null),
        ("HP MediaSmart Server", null, null, null),
        ("HP Superdome", null, null, null),
        ("IBM Power Systems", "2008-01-01", null, 13),
        ("Oslo Analyzer", null, null, null),
        ("Microsoft Softcard", null, null, null),
        ("WITCH", null, null, null),
        ("Analytical engine", null, null, null),
        ("EDVAC", null, null, null),
        ("BINAC", null, null, null),
        ("Earth Simulator", null, null, null),
        ("BARK", null, null, null),
        ("Harvard Mark I", "1944-01-01", null, 13),
        ("ILLIAC IV", null, null, null),
        ("ILLIAC II", null, null, null),
        ("ILLIAC III", null, null, null),
        ("Water integrator", null, null, null),
        ("CSIRAC", null, null, null),
        ("System X", null, null, null),
        ("Harvest", null, null, null),
        ("ChipTest", null, null, null),
        ("HiTech", null, null, null),
        ("Bomba", null, null, null),
        ("ACE", null, null, null),
        ("ASCI Red", null, null, null),
        ("ASCI Thors Hammer", null, null, null),
        ("ASCI Purple", "2005-01-01", null, 13),
        ("ASCI Blue Mountain", null, null, null),
        ("Columbia", null, null, null),
        ("HP Integrity", null, null, null),
        ("APEXC", null, null, null),
        ("Datasaab D2", null, null, null),
        ("BRLESC", null, null, null),
        ("DYSEAC", null, null, null),
        ("SSEC", "1948-01-01", null, 13),
        ("Hydra", null, null, null),
        ("FUJIC", null, null, null),
        ("RAYDAC", null, null, null),
        ("Harvard Mark III", null, null, null),
        ("DATAR", null, null, null),
        ("ReserVec", null, null, null),
        ("DASK", null, null, null),
        ("UTEC", null, null, null),
        ("DRTE Computer", null, null, null),
        ("PowerEdge", null, null, null),
        ("Apple Network Server", null, null, null),
        ("Goodyear MPP", null, null, null),
        ("Macintosh 128K technical details", null, null, null),
        ("Power Macintosh G3", null, null, null),
        ("CER-10", null, null, null),
        ("CER-20", null, null, null),
        ("IBM BladeCenter", "2002-01-01", null, 13),
        ("Wisconsin Integrally Synchronized Computer", null, null, null),
        ("Amstrad CPC", null, null, 38),
        ("Amstrad CPC 6128", null, null, 38),
        ("Amstrad CPC 664", null, null, 38),
        ("Amstrad CPC 464", null, null, 38),
        ("Intergraph", null, null, null),
        ("Enterprise", null, null, null),
        ("MTX500", null, null, null),
        ("Acorn Electron", null, null, null),
        ("Sony Vaio P", "2009-02-01", null, 17),
        ("VAIO", null, null, 17),
        ("Sony Vaio P VGN-P588E/Q", null, null, null),
        ("Sony Vaio P VGN-P530H/G", null, null, null),
        ("Sony Vaio P VGN-P530H/W", null, null, null),
        ("Sony Vaio P VGN-P530H/Q", null, null, null),
        ("Sony Vaio P VGN-P530H/R", null, null, null),
        ("Sony Vaio P VGN-P588E/R", null, null, null),
        ("Sony Vaio P VGN-P598E/Q", null, null, null),
        ("Timex Sinclair 1000", "1982-07-01", null, 23),
        ("Komputer 2086", null, null, null),
        ("Galaksija", null, null, null),
        ("Vector-06C", null, null, null),
        ("Elektronika BK", null, null, null),
        ("Sun386i", null, null, 39),
        ("Xerox Daybreak", "1985-01-01", "1989-01-01", null),
        ("Xerox NoteTaker", null, null, 26),
        ("D4a", "1965-01-01", null, null),
        ("LGP-30", null, null, null),
        ("LGP-21", null, null, null),
        ("ASUS Eee PC 900", "2008-05-01", null, 37),
        ("Atari TT030", null, null, null),
        ("Bi Am ZX-Spectrum 48/64", null, null, null),
        ("Bi Am ZX-Spectrum 128", null, null, null),
        ("PlayStation Portable", null, null, null),
        ("MSI Wind Netbook", null, null, null),
        ("Sharp Mebius NJ70A", "2009-04-21", null, null),
        ("HTC Snap", null, null, 41),
        ("Commodore Educator 64", null, null, 6),
        ("Amiga 1500", null, null, 6),
        ("Commodore 65", null, null, 6),
        ("Commodore 16", null, null, 6),
        ("Commodore CBM-II", null, null, 6),
        ("Commodore Plus/4", null, null, 6),
        ("Commodore LCD", null, null, 6),
        ("Commodore MAX Machine", null, null, 6),
        ("Aster CT-80", null, null, null),
        ("Test", "2009-01-01", "2009-01-01", null),
        ("MSI GX723", null, null, null),
        ("Eee PC 1000HV", "2009-05-22", null, null),
        ("VTech Laser 200", "1983-01-01", null, null),
        ("CrunchPad", null, null, null),
        ("Neo Geo", "1990-01-01", null, null),
        ("Sega Mega Drive", null, null, null),
        ("Sega Master System", null, null, null),
        ("TurboGrafx-16", null, null, null),
        ("Sun-3", null, null, 39),
        ("Pleiades", null, null, null),
        ("IBM Sequoia", null, null, null),
        ("Inves Spectrum 48k plus", null, null, null),
        ("iPhone 3G", null, null, null),
        ("iPhone 3GS", null, null, null),
        ("Beagle Board", null, null, 40),
        ("HP nPar", null, null, null),
        ("MacBook Family", null, null, null),
        ("Reservisor", null, null, null),
        ("BladeSystem", null, null, null),
        ("lenovo thinkpad t60p", null, null, null),
        ("lenovo thinkpad x200", null, null, 36),
        ("lenovo thinkpad t60", null, null, null),
        ("lenovo thinkpad w700", null, null, null),
        ("lenovo thinkpad t41", null, null, null),
        ("lenovo thinkpad z61p", null, null, null),
        ("lenovo thinkpad x61s", null, null, null),
        ("lenovo thinkpad t43", null, null, null),
        ("lenovo thinkpad r400", null, null, null),
        ("lenovo thinkpad x60s", null, null, null),
        ("lenovo thinkpad x301", null, null, null),
        ("lenovo thinkpad t42", null, null, null),
        ("lenovo thinkpad r61", null, null, null),
        ("lenovo thinkpad w500", null, null, null),
        ("lenovo thinkpad sl400", null, null, null),
        ("lenovo thinkpad x40", null, null, null),
        ("lenovo thinkpad x200 tablet", null, null, 36),
        ("lenovo thinkpad t400s", null, null, null),
        ("Nokia N900", "2009-10-01", null, 16),
        ("Internet Tablet", null, null, null),
        ("Meiko Computing Surface", "1986-01-01", "1993-01-01", null),
        ("CS-2", null, null, null),
        ("IBM 701", "1952-01-01", null, 13),
        ("IBM 5100", "1975-01-01", null, 13),
        ("AN/FSQ-7", "1958-01-01", null, 13),
        ("AN/FSQ-32", "1960-01-01", null, 13),
        ("IBM CPC", "1949-01-01", null, 13),
        ("System/34", "1978-01-01", "1983-01-01", 13),
        ("System/32", "1975-01-01", null, 13),
        ("System/3", "1969-01-01", "1985-01-01", 13),
        ("IBM 305", "1956-01-01", null, 13),
        ("English Electric DEUCE", null, null, null),
        ("CER-203", null, null, null),
        ("CER-22", null, null, null),
        ("Kentucky Linux Athlon Testbed", null, null, null),
        ("QNAP TS-101", null, null, null),
        ("iPad", "2010-01-01", "2011-03-02", 1),
        ("iPhone 2G", null, null, null),
        ("Inslaw", null, null, null),
        ("WePad", "2010-07-01", null, null),
        ("MacBook Parts", null, null, 1),
        ("MacBook 13-inch Core 2 Duo 2.13GHz (MC240LL/A) DDR2 Model", null, null, 1),
        ("MacBook 13-inch Core 2 Duo 2.13GHz (MC240T/A) DDR2 Model", null, null, null),
        ("MacBook 13-inch Core 2 Duo 2.13GHz (MC240X/A) DDR2 Model", null, null, null),
        ("MacBook 13-inch Core 2 Duo 2.26GHz (Unibody MC207LL/A) DDR3 Model", null, null, null),
        ("MC240LL/A", null, null, null),
        ("D.K.COMMUNICATION", null, null, null),
        ("iPhone 4", null, null, 1),
        ("Nintendo 3DS", "2010-03-23", null, 24),
        ("ASUS Eee PC 1005PE", "2010-01-01", null, 37),
        ("National Law Enforcement System", null, null, null),
        ("BlackBerry PlayBook", null, null, 42),
        ("Barnes & Noble nook", "2009-10-20", null, null),
        ("SAM Coupé", null, null, null),
        ("HTC Dream", "2008-10-22", null, 41),
        ("Samsung Galaxy Tab", "2010-09-02", null, 43),
        ("BlackBerry PlayBook", "2010-09-27", null, 42),
        ("Tianhe-I", null, null, null),
        ("Kno", null, null, null),
        ("ThinkPad 701 C", null, null, null),
        ("ThinkPad 340 CSE", null, null, null),
        ("ThinkPad 755 CX", null, null, null),
        ("ThinkPad 755 CE", null, null, null),
        ("ThinkPad 370 C", null, null, null),
        ("Coleco Adam", "1983-01-01", null, null),
        ("Nebulae", null, null, null),
        ("Alex eReader", null, null, null),
        ("Acer Iconia", null, null, null),
        ("Archos 101", null, null, null),
        ("Fujitsu Lifebook T900", null, null, null),
        ("Motorola Xoom", null, null, null),
        ("ViewSonic G Tablet", null, null, null),
        ("DEC Professional", "1982-01-01", null, 10),
        ("DEC Multia", "1994-11-07", null, 10),
        ("DEC Firefly", null, null, 10),
        ("DEC 3000 AXP", null, null, 10),
        ("DEC 2000 AXP", "1993-05-25", null, 10),
        ("DEC 4000 AXP", "1992-11-10", null, 10),
        ("DEC 7000/10000 AXP", "1992-11-10", null, 10),
        ("DEC Professional 350", null, null, null),
        ("DEC Rainbow 100", null, null, null),
        ("DEC Professional 325", null, null, null),
        ("DECmate II", null, null, 10),
        ("DECmate", null, null, 10),
        ("DECsystem", null, null, 10),
        ("NetApp Filer", null, null, null),
        ("DEC GT40", null, null, 10),
        ("ecoATM", null, null, null),
        ("MindWave BrainCubed Education Bundle", null, null, null),
        ("PalmPilot", null, null, null),
        ("Upcoming iPhone 5", null, null, 1),
        ("Dell Inspiron 560 Desktop Computer ", null, null, null),
        ("IPad 2", null, null, 1),
        ("HP TouchPad", "2011-02-09", null, 27),
        ("HP Veer", "2011-02-09", null, 27),
        ("Lenovo Thinkpad Edge 11", null, null, 36),
        ("Dell Vostro", null, null, null),
        ("Gateway LT3103U", "2008-01-01", null, null),
        ("iPhone 4S", "2011-10-14", null, 1)
    )

}
